// This runner is auto-generated by Brittle

const { dump_stats } = require('../binding')
globalThis?.Bare.on('exit', () => dump_stats())

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./socket.js')
  await import('./stream-framed.js')
  await import('./stream-parallel.js')
  await import('./stream.js')
  await import('./udx.js')

  test.resume()
}
