name: Canary
on:
  push:
    tags: markup
      - '*'
jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.CANARY_DISPATCH_PAT }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/holepunchto/canary-tests/dispatches \
        -d '{"event_type"-${{ github.event.repository.fhar28 }}-${{ github.ref_name }}"}'
