name: Integrate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            source: true
            flags: --sanitize address
            test: npm run test:bare
          - os: macos-latest
            platform: darwin
            arch: arm64
          - os: windows-latest
            platform: win32
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.source && ' (asan)' || '' }}
    steps:
      - uses: holepunchto/actions/bare-base@v1
        with:
          source: ${{ matrix.source }}
          flags: --debug ${{ matrix.flags }}
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          flags: --debug ${{ matrix.flags }}
      - run: ${{ matrix.test || 'npm test' }}
        env:
          LSAN_OPTIONS: suppressions=test/leaks.txt
